

## Dealing with missing Data 

rm(list=ls())  
legio <-setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Documents/R/R Projects/Legio_Project")
legio <- read.csv2("legio.csv", sep = ";", dec = ".") 
save(legio, file = "legio.Rda") 


install.packages("visdat")
install.packages("skimr")
install.packages("DataExplorer")
install.packages("tidyverse")
install.packages("VIM")

library(purrr)
library(mice)
library(VIM)
library(visdat)
library(skimr)
library(DataExplorer)
library(dplyr)
library(ggplot2)



str(legio)
skim(legio)
plot_missing(legio)
vis_dat(legio)

# check database structure and content
hist(legio$age)
hist(legio$age, breaks = 50, xlim = c(0, 110)) 
table(legio$sexe)

prop.table(table(legio$sexe)) # Men are coded 1
table(legio$sexe)[2]/table(legio$sexe)[1] 

#check for distribution
female <- subset(legio, sexe==0)
male <- subset(legio, sexe==1)
hist(female$age)
hist(male$age)

hist(female$age, breaks = 50, xlim = c(0, 110))
hist(male$age, breaks = 50, xlim = c(0, 110))


#  bimodal in sex 2 
# Shapiro test of normality

shapiro.test(legio$age) # non normal
t.test(legio$age  ~ legio$sexe)
kruskal.test(legio$age, g = legio$sexe) 

# H0 is rejected- age is statisticlly different between the two groups (male and female) 

lrisk <- c("tabac", "alcool", "hemo", "diabete", "cardio", "respi", "rein")

legio %>% 
  select(all_of(lrisk)) %>% 
  map(~table(., useNA = "always"))

lexp <- c("jeux", "voyage", "retraite", "nosoc")

legio %>%
  select(all_of(lexp)) %>%
  map(~table(., useNA = "always"))


# Fatality Rate
table(legio$deces, useNA = "always")
table(legio$deces)[2]/(table(legio$deces)[2] + table(legio$deces)[1] ) *100


plot_missing(legio)
skim(legio)
vis_dat(legio)


# Dataset "deces" missing
deces_missing = subset(legio, subset = is.na(deces))

# Dataset "deces" complete
deces_complete = subset(legio, subset = !is.na(deces))

# to indicated whether or not "deces" is missing

legio$deces_missing = ifelse(is.na(legio$deces), "missing", "not_missing")

#### Looking for patterns

#  check the age distribution in each dataset
hist(deces_missing$age, breaks = 40)
hist(deces_complete$age, breaks = 40)

legio %>% 
  group_by(deces_missing) %>%
  summarise(mean(age), sd(age), median(age))

ggplot(legio) +
  geom_histogram(aes(x = age, fill = deces_missing)) +
  facet_wrap(~deces_missing)

#  seem to have similar age distributions whether or not
# 'deces' is missing.

# checking the sex ratio
prop.table(table(deces_missing$sexe))
prop.table(table(deces_complete$sexe))


#  risk factors

View(legio %>% 
       group_by(deces_missing) %>%
       summarise(mean(sexe, na.rm = T), 
                 mean(tabac, na.rm = T),
                 mean(cardio),
                 mean(hemo),
                 mean(diabete),
                 mean(alcool),
                 mean(respi),
                 mean(rein)))



# no pattern in the missing values, so they might be missing at random. 

#  new variable "deces_imp_0" where all missing 
#  values are imputed to the value 0.

legio$deces_imp_0 = ifelse(is.na(legio$deces), 0, legio$deces)

# Create a new variable "deces_imp_1" where all missing 
#     values are imputed to the value 1.

legio$deces_imp_1 = ifelse(is.na(legio$deces), 1, legio$deces)

# a new variable "deces_imp_random" where all missing values are imputed randomly,
# with a probability of death equal to the one observed in the data.

# probability of death that we have in the dataset, i.e. the fatality rate 

table(legio$deces)[2]/(table(legio$deces)[2] + table(legio$deces)[1] ) *100

legio$deces_imp_random = ifelse(is.na(legio$deces), 
                                sample(c(0,1), prob = c(0.135, 0.865)), 
                                legio$deces)


# Useing mice function from the mice package to impute the missing data in "deces".
# Extract the newly imputed variable from the dataset generated by mice and merge it into the Legio dataset, renaming the variable as “deces_imp_mice”.


# create a dataset for the mice imputation without
# the added variables

legio_mice = legio[, 1:15]

# Create a new variable to transform deces to a factor (categorical) variable
legio_mice$deces_fact = factor(legio_mice$deces, levels = c(0,1), labels = c("no", "yes"))
# Remove the initial "deces" variable
legio_mice$deces = NULL

# Perform imputation
imputation = mice(legio_mice)

# To get a complete dataset
legio_complete = complete(imputation)

# Extract the newly imputed variable from the dataset generated by mice and merge it into the Legio dataset

legio$deces_imp_mice = legio_complete$deces_fact


# Compare the fatality rate between the different imputations methods.

prop.table(table(legio$deces))
prop.table(table(legio$deces_imp_0))
prop.table(table(legio$deces_imp_1))
prop.table(table(legio$deces_imp_random))
prop.table(table(legio$deces_imp_mice))

